### ISSUE TITLE
Every other key stroke fails to return results

### ISSUE THREAD

**Issue by bmalinconico** [ms-jpq/coq_nvim#72]
Thanks for all your work. I'm working on seeing if this could replace the last completion engine I was using and ran into the following odd behavior.

This occurs in multiple languages, but the gist of the problem is that as I type, I'm only getting results on every other keystroke.

![Aug-17-2021 13-45-31](https://user-images.githubusercontent.com/19909708/129775473-22f0dd5c-ebb0-4f2f-b4ab-f2d5eee03f7a.gif)

**Comment by ms-jpq** [comment]
can you pull latest again and try, i think i pushed a bad commit last night, just reverted it.

sorry about the inconvenience

**Comment by iverberk** [comment]
I just pulled latest version of the plugin (with Packer) and the problem is still there. It only completes when you enter an odd number of characters.

**Comment by ms-jpq** [comment]
sorry about that

https://github.com/ms-jpq/coq_nvim/pull/74

does this fix it for you?

there was a hidden race condition and when I made it slightly faster last night I think it begun to trigger for people, i didnt trigger for me until i ran in in a clean docker image

**Comment by bmalinconico** [comment]
@iverberk It's going to be one of the funnies bugs I have seen if the root cause is actually related to the evenness!

**Comment by bmalinconico** [comment]
@ms-jpq I'm seeing the auto complete window remain up, but it looses a bunch of sources.


![Aug-17-2021 15-04-33](https://user-images.githubusercontent.com/19909708/129785630-2421d0a1-ee13-499f-90a9-f1c432161096.gif)

**Comment by ms-jpq** [comment]
LOL thats even werider

**Comment by iverberk** [comment]
The problem with the intermittent completion results seems fixed, thanks for the quick turnaround and the awesome plugin!

**Comment by ms-jpq** [comment]
@bmalinconico wait, that could just be from `gopls` (it looks like gopls to me) not responding within the default`0.088` seconds for the second result, its super hard to tell from the gif.

If its a timeout issue, you can increase the default timeout to be a bit longer.

`coq_settings.limits.completion_auto_timeout` is the setting.

---

The timeouts in `coq.nvim` is a little weird. Like other plugins might have a hard timeout for all sources, but `coq.nvim` will actually wait pass the timeout if 1) user has not touched their keyboard, and 2) no sources have not responded so far.

Alot of times, this means that `LSP` will the the slowest source, and if no other sources can find anything, LSP will be waited on indefinitely until it returns with results.

This is done to improve user experience for slower LSPs, but it also makes testing timeouts super confusing, since the timeout **only applies to your second last keystroke**, and **only when there has been as least one source that responded**.

**Comment by ms-jpq** [comment]
also i swear to god im not a nazi, i use a lot of 8s and 6s in my constants because they are Chinese lucky numbers.

**Comment by bmalinconico** [comment]
I'll give that a try. I think we can close this issue now. Thanks for the quick fix.
